name: helgihrafn
namespace: prod-helgihrafn
replicaCount: 1

image:
  repository: ghcr.io/helgihg/helgihrafn.is
  tag: latest
  pullPolicy: Always

ingress:
  className: traefik
  host: helgihrafn.is
  tls:
    issuer: letsencrypt-staging
    secretName: helgihrafn-tls
